// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.0
// source: constant/constant.proto

package constant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Constant int32

const (
	Constant_operationID    Constant = 0
	Constant_opUserID       Constant = 1
	Constant_connID         Constant = 2
	Constant_opUserPlatform Constant = 3
	Constant_token          Constant = 4
	Constant_customHeader   Constant = 5
	Constant_checkKey       Constant = 6
	Constant_triggerID      Constant = 7
	Constant_remoteAddr     Constant = 8
)

// Enum value maps for Constant.
var (
	Constant_name = map[int32]string{
		0: "operationID",
		1: "opUserID",
		2: "connID",
		3: "opUserPlatform",
		4: "token",
		5: "customHeader",
		6: "checkKey",
		7: "triggerID",
		8: "remoteAddr",
	}
	Constant_value = map[string]int32{
		"operationID":    0,
		"opUserID":       1,
		"connID":         2,
		"opUserPlatform": 3,
		"token":          4,
		"customHeader":   5,
		"checkKey":       6,
		"triggerID":      7,
		"remoteAddr":     8,
	}
)

func (x Constant) Enum() *Constant {
	p := new(Constant)
	*p = x
	return p
}

func (x Constant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Constant) Descriptor() protoreflect.EnumDescriptor {
	return file_constant_constant_proto_enumTypes[0].Descriptor()
}

func (Constant) Type() protoreflect.EnumType {
	return &file_constant_constant_proto_enumTypes[0]
}

func (x Constant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Constant.Descriptor instead.
func (Constant) EnumDescriptor() ([]byte, []int) {
	return file_constant_constant_proto_rawDescGZIP(), []int{0}
}

var File_constant_constant_proto protoreflect.FileDescriptor

var file_constant_constant_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6d, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2a, 0x93, 0x01, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x44, 0x10, 0x02, 0x12, 0x12,
	0x0a, 0x0e, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x10, 0x04, 0x12, 0x10, 0x0a,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x05, 0x12,
	0x0c, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x10, 0x06, 0x12, 0x0d, 0x0a,
	0x09, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x49, 0x44, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x10, 0x08, 0x42, 0x29, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6e, 0x67, 0x6c,
	0x75, 0x6e, 0x61, 0x72, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_constant_constant_proto_rawDescOnce sync.Once
	file_constant_constant_proto_rawDescData = file_constant_constant_proto_rawDesc
)

func file_constant_constant_proto_rawDescGZIP() []byte {
	file_constant_constant_proto_rawDescOnce.Do(func() {
		file_constant_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_constant_constant_proto_rawDescData)
	})
	return file_constant_constant_proto_rawDescData
}

var file_constant_constant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constant_constant_proto_goTypes = []interface{}{
	(Constant)(0), // 0: im.constant.constant
}
var file_constant_constant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constant_constant_proto_init() }
func file_constant_constant_proto_init() {
	if File_constant_constant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constant_constant_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constant_constant_proto_goTypes,
		DependencyIndexes: file_constant_constant_proto_depIdxs,
		EnumInfos:         file_constant_constant_proto_enumTypes,
	}.Build()
	File_constant_constant_proto = out.File
	file_constant_constant_proto_rawDesc = nil
	file_constant_constant_proto_goTypes = nil
	file_constant_constant_proto_depIdxs = nil
}
